!function(n,e){"object"==typeof exports&&"undefined"!=typeof module?e(exports,require("react")):"function"==typeof define&&define.amd?define(["exports","react"],e):e(((n=n||self).index=n.index||{},n.index.tsx={}),n.React)}(this,(function(n,e){"use strict";function t(n){if(n&&"undefined"!=typeof window&&"undefined"!=typeof document&&void 0!==document.head){var e=function(n){var e=5381,t=n.length-1,o="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".split("");if("string"==typeof n)for(;t>-1;t--)e+=(e<<5)+n.charCodeAt(t);else for(;t>-1;t--)e+=(e<<5)+n[t];var r=2147483647&e,i="";do{i+=o[63&r]}while(r>>=6);return i}(n);if(!document.getElementById(e)){var t=document.createElement("style");return t.id=e,t.innerHTML=n,document.head.appendChild(t),n}}}e=e&&e.hasOwnProperty("default")?e.default:e,t("._button_1q9fy_1 {\n  cursor: pointer;\n  position: relative;\n  display: inline-block;\n  transition: 0.1s;\n  overflow: hidden;\n  border-radius: 4px;\n  color: white;\n  background-color: #351eff;\n}\n._button_1q9fy_1 ._realButton_1q9fy_11 {\n  width: 100%;\n  border: none;\n  outline: none;\n  color: inherit;\n  cursor: inherit;\n  font-size: inherit;\n  text-align: center;\n  font-weight: inherit;\n  display: inline-block;\n  padding: 0.5em 2em;\n  background-color: transparent;\n}\n._button_1q9fy_1._link_1q9fy_24 {\n  color: #351eff;\n  background-color: transparent;\n  box-shadow: none !important;\n}\n._button_1q9fy_1._small_1q9fy_29 {\n  font-size: 12px;\n  font-weight: 200;\n}\n._button_1q9fy_1._large_1q9fy_33 {\n  font-size: 16px;\n  font-weight: 600;\n}\n._button_1q9fy_1._normal_1q9fy_37 {\n  font-size: 14px;\n  font-weight: 400;\n}\n._button_1q9fy_1._normal_1q9fy_37 {\n  top: -2px;\n  transform: scale(1.02, 1.02);\n  box-shadow: 0px 8px 8px -2px rgba(0, 0, 0, 0.3);\n}\n._button_1q9fy_1._loading_1q9fy_46 {\n  top: 0px;\n  transform: scale(1, 1);\n  box-shadow: 0px 0px 0px 0px rgba(0, 0, 0, 0.33333333);\n}\n._button_1q9fy_1._disable_1q9fy_51 {\n  top: 0px;\n  transform: scale(1, 1);\n  box-shadow: 0px 0px 0px 0px rgba(0, 0, 0, 0.33333333);\n}\n._button_1q9fy_1:active {\n  top: 0px;\n  transform: scale(1, 1);\n  box-shadow: 0px 0px 0px 0px rgba(0, 0, 0, 0.33333333);\n}\n");var o={button:"_button_1q9fy_1",realButton:"_realButton_1q9fy_11",link:"_link_1q9fy_24",small:"_small_1q9fy_29",large:"_large_1q9fy_33",normal:"_normal_1q9fy_37",loading:"_loading_1q9fy_46",disable:"_disable_1q9fy_51"};
/*! *****************************************************************************
  Copyright (c) Microsoft Corporation. All rights reserved.
  Licensed under the Apache License, Version 2.0 (the "License"); you may not use
  this file except in compliance with the License. You may obtain a copy of the
  License at http://www.apache.org/licenses/LICENSE-2.0

  THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
  WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
  MERCHANTABLITY OR NON-INFRINGEMENT.

  See the Apache Version 2.0 License for specific language governing permissions
  and limitations under the License.
  ***************************************************************************** */t(void 0);var r={};const i=n=>{const{style:t,className:o,children:i}=n,a=function(n,e){var t={};for(var o in n)Object.prototype.hasOwnProperty.call(n,o)&&e.indexOf(o)<0&&(t[o]=n[o]);if(null!=n&&"function"==typeof Object.getOwnPropertySymbols){var r=0;for(o=Object.getOwnPropertySymbols(n);r<o.length;r++)e.indexOf(o[r])<0&&Object.prototype.propertyIsEnumerable.call(n,o[r])&&(t[o[r]]=n[o[r]])}return t}(n,["style","className","children"]),l=function(n){const e=[],t=n=>{if(n)if(Array.isArray(n))for(let e=0;e<n.length;e++)t(n[e]);else n&&e.push(n)};return t(n),e.join(" ")}(o),f=function(n){const e={},t=n=>{if(n&&Array.isArray(n))for(let e=0;e<n.length;e++)t(n[e]);else n&&Object.assign(e,n)};return t(n),e}(t),s=[r.container,l].filter(Boolean).join(" ").trim();return e.createElement("div",Object.assign({className:s,style:f},a),n.children)},a=n=>{const[t,r]=e.useState("normal"),{size:a="normal",type:l="normal",disable:f}=n,s="loading"===t?"处理中...":n.children;return e.createElement(i,{style:[n.style],className:[o.button,o[l],o[a],o[t],n.className]},e.createElement("button",{type:n.htmlType,disabled:f,className:[o.realButton,o[l]].join(" "),onClick:()=>{if("normal"!==t)return;if(!n.onClick)return;const e=n.onClick();return e instanceof Promise?(r("loading"),e.finally(()=>r("normal")),e):void 0}},s))};n.Button=a,n.default=a,Object.defineProperty(n,"__esModule",{value:!0})}));
//# sourceMappingURL=index.js.map
