!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports):"function"==typeof define&&define.amd?define(["exports"],t):t(((e=e||self).controller=e.controller||{},e.controller.ts={}))}(this,(function(e){"use strict";
/*! *****************************************************************************
    Copyright (c) Microsoft Corporation. All rights reserved.
    Licensed under the Apache License, Version 2.0 (the "License"); you may not use
    this file except in compliance with the License. You may obtain a copy of the
    License at http://www.apache.org/licenses/LICENSE-2.0

    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
    WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
    MERCHANTABLITY OR NON-INFRINGEMENT.

    See the Apache Version 2.0 License for specific language governing permissions
    and limitations under the License.
    ***************************************************************************** */
function t(e,t,o,r){var n,i=arguments.length,s=i<3?t:null===r?r=Object.getOwnPropertyDescriptor(t,o):r;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)s=Reflect.decorate(e,t,o,r);else for(var c=e.length-1;c>=0;c--)(n=e[c])&&(s=(i<3?n(s):i>3?n(t,o,s):n(t,o))||s);return i>3&&s&&Object.defineProperty(t,o,s),s}function o(e){return(o="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}function r(e,t,r){var n=r.value;if("function"!=typeof n)throw new TypeError("@boundMethod decorator can only be applied to methods not: ".concat(o(n)));var i=!1;return{configurable:!0,get:function(){if(i||this===e.prototype||this.hasOwnProperty(t)||"function"!=typeof n)return n;var o=n.bind(this);return i=!0,Object.defineProperty(this,t,{configurable:!0,get:function(){return o},set:function(e){n=e,delete this[t]}}),i=!1,o},set:function(e){n=e}}}function n(e){var t;return"undefined"!=typeof Reflect&&"function"==typeof Reflect.ownKeys?t=Reflect.ownKeys(e.prototype):(t=Object.getOwnPropertyNames(e.prototype),"function"==typeof Object.getOwnPropertySymbols&&(t=t.concat(Object.getOwnPropertySymbols(e.prototype)))),t.forEach((function(t){if("constructor"!==t){var o=Object.getOwnPropertyDescriptor(e.prototype,t);"function"==typeof o.value&&Object.defineProperty(e.prototype,t,r(e,t,o))}})),e}function i(){return 1===arguments.length?n.apply(void 0,arguments):r.apply(void 0,arguments)}class s{constructor(){this.subscribers=new Map}addListener(e){const t=Symbol();return this.subscribers.set(t,e),()=>this.removeListener(t)}removeListener(e){return this.subscribers.delete(e)}dispatchSubscribers(){return e=this,t=void 0,r=function*(){const e=Array.from(this.subscribers.values());for(let t=0;t<e.length;t++)yield e[t]()},new((o=void 0)||(o=Promise))((function(n,i){function s(e){try{u(r.next(e))}catch(e){i(e)}}function c(e){try{u(r.throw(e))}catch(e){i(e)}}function u(e){e.done?n(e.value):new o((function(t){t(e.value)})).then(s,c)}u((r=r.apply(e,t||[])).next())}));var e,t,o,r}}t([i],s.prototype,"addListener",null),t([i],s.prototype,"removeListener",null),t([i],s.prototype,"dispatchSubscribers",null);class c extends s{constructor(){super(...arguments),this.lastID=0,this.overlays=new Map}insert(e){const t=++this.lastID;return this.overlays.set(t,e),this.dispatchSubscribers(),()=>this.remove(t)}remove(e){this.overlays.delete(e)&&this.dispatchSubscribers()}}t([i],c.prototype,"insert",null),t([i],c.prototype,"remove",null);const u=new c,{insert:f,remove:l}=u;e.Controller=c,e.default=u,e.insert=f,e.isOverlayRender=function(e){const{render:t}=e;return!!(t&&t instanceof Function)},e.remove=l,Object.defineProperty(e,"__esModule",{value:!0})}));
//# sourceMappingURL=controller.js.map
