!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports,require("react")):"function"==typeof define&&define.amd?define(["exports","react"],t):t(((e=e||self).container=e.container||{},e.container.tsx={}),e.React)}(this,(function(e,t){"use strict";function n(e){if(e&&"undefined"!=typeof window&&"undefined"!=typeof document&&void 0!==document.head){var t=function(e){var t=5381,n=e.length-1,r="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".split("");if("string"==typeof e)for(;n>-1;n--)t+=(t<<5)+e.charCodeAt(n);else for(;n>-1;n--)t+=(t<<5)+e[n];var o=2147483647&t,s="";do{s+=r[63&o]}while(o>>=6);return s}(e);if(!document.getElementById(t)){var n=document.createElement("style");return n.id=t,n.innerHTML=e,document.head.appendChild(n),e}}}function r(e,t,n,r){var o,s=arguments.length,i=s<3?t:null===r?r=Object.getOwnPropertyDescriptor(t,n):r;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)i=Reflect.decorate(e,t,n,r);else for(var c=e.length-1;c>=0;c--)(o=e[c])&&(i=(s<3?o(i):s>3?o(t,n,i):o(t,n))||i);return s>3&&i&&Object.defineProperty(t,n,i),i}t=t&&t.hasOwnProperty("default")?t.default:t,n("._overlay_1y2vl_1 {\n  top: 0;\n  left: 0;\n  z-index: 1;\n  position: fixed;\n}\n._entitiesRoot_1y2vl_7 {\n  top: 0;\n  left: 0;\n  position: absolute;\n}\n._mask_1y2vl_12 {\n  top: 0;\n  left: 0;\n  width: 100vw;\n  height: 100vh;\n  overflow: auto;\n  position: absolute;\n  background-color: rgba(0, 0, 0, 0.01);\n}\n");var o="_overlay_1y2vl_1",s="_entitiesRoot_1y2vl_7",i="_mask_1y2vl_12";function c(e){return(c="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}function l(e,t,n){var r=n.value;if("function"!=typeof r)throw new TypeError("@boundMethod decorator can only be applied to methods not: ".concat(c(r)));var o=!1;return{configurable:!0,get:function(){if(o||this===e.prototype||this.hasOwnProperty(t)||"function"!=typeof r)return r;var n=r.bind(this);return o=!0,Object.defineProperty(this,t,{configurable:!0,get:function(){return n},set:function(e){r=e,delete this[t]}}),o=!1,n},set:function(e){r=e}}}function a(e){var t;return"undefined"!=typeof Reflect&&"function"==typeof Reflect.ownKeys?t=Reflect.ownKeys(e.prototype):(t=Object.getOwnPropertyNames(e.prototype),"function"==typeof Object.getOwnPropertySymbols&&(t=t.concat(Object.getOwnPropertySymbols(e.prototype)))),t.forEach((function(t){if("constructor"!==t){var n=Object.getOwnPropertyDescriptor(e.prototype,t);"function"==typeof n.value&&Object.defineProperty(e.prototype,t,l(e,t,n))}})),e}function u(){return 1===arguments.length?a.apply(void 0,arguments):l.apply(void 0,arguments)}n(void 0);var f={};const p=e=>{const{style:n,className:r,children:o}=e,s=
/*! *****************************************************************************
    Copyright (c) Microsoft Corporation. All rights reserved.
    Licensed under the Apache License, Version 2.0 (the "License"); you may not use
    this file except in compliance with the License. You may obtain a copy of the
    License at http://www.apache.org/licenses/LICENSE-2.0

    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
    WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
    MERCHANTABLITY OR NON-INFRINGEMENT.

    See the Apache Version 2.0 License for specific language governing permissions
    and limitations under the License.
    ***************************************************************************** */
function(e,t){var n={};for(var r in e)Object.prototype.hasOwnProperty.call(e,r)&&t.indexOf(r)<0&&(n[r]=e[r]);if(null!=e&&"function"==typeof Object.getOwnPropertySymbols){var o=0;for(r=Object.getOwnPropertySymbols(e);o<r.length;o++)t.indexOf(r[o])<0&&Object.prototype.propertyIsEnumerable.call(e,r[o])&&(n[r[o]]=e[r[o]])}return n}(e,["style","className","children"]),i=function(e){const t=[],n=e=>{if(e)if(Array.isArray(e))for(let t=0;t<e.length;t++)n(e[t]);else e&&t.push(e)};return n(e),t.join(" ")}(r),c=function(e){const t={},n=e=>{if(e&&Array.isArray(e))for(let t=0;t<e.length;t++)n(e[t]);else e&&Object.assign(t,e)};return n(e),t}(n),l=[f.container,i].filter(Boolean).join(" ").trim();return t.createElement("div",Object.assign({className:l,style:c},s),e.children)};class y{constructor(){this.subscribers=new Map}addListener(e){const t=Symbol();return this.subscribers.set(t,e),()=>this.removeListener(t)}removeListener(e){return this.subscribers.delete(e)}dispatchSubscribers(){return e=this,t=void 0,r=function*(){const e=Array.from(this.subscribers.values());for(let t=0;t<e.length;t++)yield e[t]()},new((n=void 0)||(n=Promise))((function(o,s){function i(e){try{l(r.next(e))}catch(e){s(e)}}function c(e){try{l(r.throw(e))}catch(e){s(e)}}function l(e){e.done?o(e.value):new n((function(t){t(e.value)})).then(i,c)}l((r=r.apply(e,t||[])).next())}));var e,t,n,r}}r([u],y.prototype,"addListener",null),r([u],y.prototype,"removeListener",null),r([u],y.prototype,"dispatchSubscribers",null);class d extends y{constructor(){super(...arguments),this.lastID=0,this.overlays=new Map}insert(e){const t=++this.lastID;return this.overlays.set(t,e),this.dispatchSubscribers(),()=>this.remove(t)}remove(e){this.overlays.delete(e)&&this.dispatchSubscribers()}}r([u],d.prototype,"insert",null),r([u],d.prototype,"remove",null);const h=new d,{insert:v,remove:b}=h;class m extends t.Component{constructor(e){super(e),this.cancelListener=this.controller.addListener(()=>{this.setState({overlays:this.controller.overlays})})}generateCloser(e){return t=>b(e)}componentWillUnmount(){this.cancelListener&&this.cancelListener()}get controller(){return this.props.controller||h}get overlayEntities(){const{overlays:e}=this.state||{};if(e&&e.size>0){return Array.from(e.entries()).map(([e,n])=>{if(!function(e){const{render:t}=e;return!!(t&&t instanceof Function)}(n))return null;const r=n.isShowMask,o=n.enableCloseByMask?this.generateCloser(e):void 0;return t.createElement(p,{className:[s],style:{zIndex:e},key:String(e)},r&&t.createElement(p,{className:[i],onClick:o}),n.render(this.generateCloser(e)))})}}render(){return[this.props.children,t.createElement(p,{className:[o]},this.overlayEntities)]}}r([u],m.prototype,"generateCloser",null),e.default=m,Object.defineProperty(e,"__esModule",{value:!0})}));
//# sourceMappingURL=container.js.map
