!function(e,n){"object"==typeof exports&&"undefined"!=typeof module?n(exports,require("react")):"function"==typeof define&&define.amd?define(["exports","react"],n):n(((e=e||self).index=e.index||{},e.index.tsx={}),e.React)}(this,(function(e,n){"use strict";function l(e){if(e&&"undefined"!=typeof window&&"undefined"!=typeof document&&void 0!==document.head){var n=function(e){var n=5381,l=e.length-1,t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".split("");if("string"==typeof e)for(;l>-1;l--)n+=(n<<5)+e.charCodeAt(l);else for(;l>-1;l--)n+=(n<<5)+e[l];var r=2147483647&n,_="";do{_+=t[63&r]}while(r>>=6);return _}(e);if(!document.getElementById(n)){var l=document.createElement("style");return l.id=n,l.innerHTML=e,document.head.appendChild(l),e}}}n=n&&n.hasOwnProperty("default")?n.default:n,l("._title_gzrxe_1 {\n  color: black;\n  background-color: transparent;\n}\n._title_gzrxe_1 ._subtitle_gzrxe_5 {\n  opacity: 0.5;\n  color: black;\n}\n._level-1_gzrxe_9 {\n  font-size: 40px;\n  font-weight: bold;\n}\n._level-1_gzrxe_9 ._subtitle_gzrxe_5 {\n  font-size: 26px;\n  font-weight: normal;\n}\n._level-2_gzrxe_17 {\n  font-size: 32px;\n  font-weight: bold;\n}\n._level-2_gzrxe_17 ._subtitle_gzrxe_5 {\n  font-size: 20px;\n  font-weight: normal;\n}\n._level-3_gzrxe_25 {\n  font-size: 28px;\n  font-weight: bold;\n}\n._level-3_gzrxe_25 ._subtitle_gzrxe_5 {\n  font-size: 16px;\n  font-weight: normal;\n}\n._level-4_gzrxe_33 {\n  font-size: 20px;\n  font-weight: bold;\n}\n._level-4_gzrxe_33 ._subtitle_gzrxe_5 {\n  display: none;\n  font-weight: normal;\n}\n._level-5_gzrxe_41 {\n  font-size: 16px;\n  font-weight: bold;\n}\n._level-5_gzrxe_41 ._subtitle_gzrxe_5 {\n  display: none;\n  font-weight: normal;\n}\n._level-6_gzrxe_49 {\n  font-size: 14px;\n  font-weight: bold;\n}\n._level-6_gzrxe_49 ._subtitle_gzrxe_5 {\n  display: none;\n  font-weight: normal;\n}\n");var t={title:"_title_gzrxe_1",subtitle:"_subtitle_gzrxe_5","level-1":"_level-1_gzrxe_9","level-2":"_level-2_gzrxe_17","level-3":"_level-3_gzrxe_25","level-4":"_level-4_gzrxe_33","level-5":"_level-5_gzrxe_41","level-6":"_level-6_gzrxe_49",level1:"_level-1_gzrxe_9",level2:"_level-2_gzrxe_17",level3:"_level-3_gzrxe_25",level4:"_level-4_gzrxe_33",level5:"_level-5_gzrxe_41",level6:"_level-6_gzrxe_49"};
/*! *****************************************************************************
    Copyright (c) Microsoft Corporation. All rights reserved.
    Licensed under the Apache License, Version 2.0 (the "License"); you may not use
    this file except in compliance with the License. You may obtain a copy of the
    License at http://www.apache.org/licenses/LICENSE-2.0

    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
    WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
    MERCHANTABLITY OR NON-INFRINGEMENT.

    See the Apache Version 2.0 License for specific language governing permissions
    and limitations under the License.
    ***************************************************************************** */l(void 0);var r={};const _=e=>{const{style:l,className:t,children:_}=e,o=function(e,n){var l={};for(var t in e)Object.prototype.hasOwnProperty.call(e,t)&&n.indexOf(t)<0&&(l[t]=e[t]);if(null!=e&&"function"==typeof Object.getOwnPropertySymbols){var r=0;for(t=Object.getOwnPropertySymbols(e);r<t.length;r++)n.indexOf(t[r])<0&&Object.prototype.propertyIsEnumerable.call(e,t[r])&&(l[t[r]]=e[t[r]])}return l}(e,["style","className","children"]),i=function(e){const n=[],l=e=>{if(e)if(Array.isArray(e))for(let n=0;n<e.length;n++)l(e[n]);else e&&n.push(e)};return l(e),n.join(" ")}(t),s=function(e){const n={},l=e=>{if(e&&Array.isArray(e))for(let n=0;n<e.length;n++)l(e[n]);else e&&Object.assign(n,e)};return l(e),n}(l),a=[r.container,i].filter(Boolean).join(" ").trim();return n.createElement("div",Object.assign({className:a,style:s},o),e.children)},o=e=>{const{level:l=1,title:r,subtitle:o}=e;return n.createElement(_,{className:[t.title,t[`level-${l}`],e.className],style:e.style},n.createElement("div",null,r),n.createElement("div",{className:t.subtitle},o))};e.Title=o,e.default=o,Object.defineProperty(e,"__esModule",{value:!0})}));
//# sourceMappingURL=index.js.map
